### ISSUE TITLE
Cannot connect to api and fetch assets

### ISSUE THREAD

**Issue by ahpohl** [vale46n1/immich_duplicate_finder#10]
I want to try your duplicate detection script (Version: v0.0.6). However, after entering the immich server url and the api key, the web app cannot connect and fetch the assets:

```
Error fetching assets: HTTPConnectionPool(host='odroidc4.home.arpa', port=2283): Read timed out. (read timeout=10)
```

I entered the server like so: `http://odroidc4.home.arpa:2283` (with and without trailing '/'). To verify the api key and the immich server is responding, I connect with `immich-cli`:

```
$ immich login-key http://odroidc4.home.arpa:2283/api jeIKEyNcGmvt8ErTGPSBy1sCK0608xjk2dDf...
Executing API key auth flow...
Logged in as alex@...
Wrote auth info to /home/alex/.config/immich/auth.yml

$ immich server-info
Server is running version 1.99.0
Supported image types: 3fr,ari,arw,avif,bmp,cap,cin,cr2,cr3,crw,dcr,dng,erf,fff,gif,heic,heif,hif,iiq,insp,jpe,jpeg,jpg,jxl,k25,kdc,mrw,nef,orf,ori,pef,png,psd,raf,raw,rw2,rwl,sr2,srf,srw,svg,tif,tiff,webp,x3f
Supported video types: 3gp,avi,flv,insv,m2ts,m4v,mkv,mov,mp4,mpg,mts,webm,wmv
Images: 14678, Videos: 541, Total: 15219
```

Any ideas?

**Comment by vale46n1** [comment]
Try timeout 2000

**Comment by ahpohl** [comment]
Thanks, with timeout 2000 it works now

**Comment by vale46n1** [comment]
I'll improve that part of UI. Moreover this night I'll release also the new FAISS algorithm to detect duplicated
