### ISSUE TITLE
Cant delete images

### ISSUE THREAD

**Issue by moxli** [vale46n1/immich_duplicate_finder#16]
When I click the delete button on a duplicate the duplicate finder restarts and the duplicate is not deleted.

![image](https://github.com/vale46n1/immich_duplicate_finder/assets/26149616/6e1bbcb6-b7db-4bc7-accb-e1074b14dbad)

When it finishes each time 1045 duplicates are found.

My Settings:
![image](https://github.com/vale46n1/immich_duplicate_finder/assets/26149616/ec47e48f-e851-432e-a02d-911725001194)

There are no log messages displayed after clicking the delete button.

**Comment by random1planet** [comment]
I have been having the same issue and thought I was missing something, but this still could be the same.

**Comment by mariosemes** [comment]
I was thinking that I'm going crazy, same thing here. Whatever I do the Index processing restarts and ignores the selected delete.

**Comment by mariosemes** [comment]
https://github.com/vale46n1/immich_duplicate_finder/assets/2343219/495a74b8-d76d-4619-b77f-ab4aa0ca150b

**Comment by random1planet** [comment]
There could be something we are missing. I'm not a developer but reasonably technical. I'm assuming there is something I am doing wrong and maybe the app doesn't have the right permissions or something through the API.

On 16 Apr 2024 18:40, TMC ***@***.***> wrote:

https://github.com/vale46n1/immich_duplicate_finder/assets/2343219/495a74b8-d76d-4619-b77f-ab4aa0ca150b

**Comment by vale46n1** [comment]
Thanks for bringing this to my attention. I'll review the current implementation. I'm also planning to refactor the code and integrate a React frontend, which should enhance the functionality and user experience significantly

**Comment by random1planet** [comment]
Just say this is an amazing piece of work and like magic to find all the duplicates, it wasnt that difficult to set up after blasting few a through Linux distros. So thanks for your work so far 🙂
