### ISSUE TITLE
Missing information for one or both assets

### ISSUE THREAD

**Issue by agross** [vale46n1/immich_duplicate_finder#18]
<img width="716" alt="2024-04-17_09-10-37" src="https://github.com/vale46n1/immich_duplicate_finder/assets/16245/4e029031-ac48-4775-a96c-40f0d90860b7">

This is logged: 

```
Skipping non-image asset_id cca82518-6646-47f7-b6d4-029afe05de4a with Content-Type: application/json; charset=utf-8
```

There is nothing related to the ID  of `cca82518...` in the Immich DB (`public.assets`) and no file in the filesystem with that name (e.g. preview image). 

Does the app handle deleted assets correctly?

**Comment by vale46n1** [comment]
Yes, when you delete an image in Immich, the image code remains in the duplicate database. If you rerun the duplicate finder, it will not be able to locate the image in Immich and will return an error. I will update the deletion code to also remove the corresponding entry from the database.

**Comment by vale46n1** [comment]
Anyhow sometime Immich return a json file. This will be skipped. Anyhow seems that you don't have duplicate. What I'll implement soon are similiar image finder. Maybe changing frontend from streamlit to react....
