### ISSUE TITLE
Can't start docker container

### ISSUE THREAD

**Issue by JW-CH** [vale46n1/immich_duplicate_finder#19]
When trying to start the docker container, the following message appears:

```bash
PS C:\Dev\immich_duplicate_finder\docker> docker-compose up -d
[+] Building 0.0s (0/0)                                                                                  docker:default
unable to prepare context: path "C:\\Dev\\immich_duplicate_finder\\docker\\Dockerfile" not found
PS C:\Dev\immich_duplicate_finder\docker>
```

Running on windows

**Comment by vale46n1** [comment]
In the meantime you can use the script as per my instruction. If u are
using windows you can create a quick Bat file for automatic opening

Il mer 17 apr 2024, 11:21 Jan ***@***.***> ha scritto:

**Comment by vale46n1** [comment]
@mmomjian can you have a look when u have time?
