### ISSUE TITLE
Blank window when app is deployed via Docker

### ISSUE THREAD

**Issue by xinput** [vale46n1/immich_duplicate_finder#27]
Hello,

thanks for your work which looks very promising.

I trief to deploy this tool via Docker (tested on Debian and also on Windows) in both cases, as soon as the app is started and I open it in my browser I'm getting a more or less "blank" window
see screemshot below 
![21 04 2024-11_56_07](https://github.com/vale46n1/immich_duplicate_finder/assets/11652924/5e512cc2-e232-451a-851c-d5bf2abdd52f)
I can put it my Login Details but still nothing happens.

The output of the container logs looks as follows:

```
immich-duplicate-finder  | 
immich-duplicate-finder  | Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.
immich-duplicate-finder  | 
immich-duplicate-finder  | 
immich-duplicate-finder  |   You can now view your Streamlit app in your browser.
immich-duplicate-finder  | 
immich-duplicate-finder  |   Network URL: http://172.18.0.2:8501
immich-duplicate-finder  |   External URL: http://178.201.200.190:8501
immich-duplicate-finder  | 
immich-duplicate-finder  | Downloading: "https://download.pytorch.org/models/resnet152-f82ba261.pth" to /root/.cache/torch/hub/checkpoints/resnet152-f82ba261.pth
100.0%24-04-21T09:43:42.615733784Z %-finder  | 
```

any idea what's going on or where I can start debugging?

Thanks

**Comment by vale46n1** [comment]
did you solve?

**Comment by RobHofmann** [comment]
same here.

**Comment by vale46n1** [comment]
@mmomjian can you have a look?

**Comment by vale46n1** [comment]
ok, seems is downloading the pytorch models. Same even leaving 10min downloding?

**Comment by RobHofmann** [comment]
> ok, seems is downloading the pytorch models. Same even leaving 10min downloding?

its been running for over 36 hours now. So i would say yes :). 

Logs attached:
```

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.


  You can now view your Streamlit app in your browser.

  Network URL: http://172.19.0.27:8501
  External URL: http://213.10.112.40:8501

Downloading: "https://download.pytorch.org/models/resnet152-f82ba261.pth" to /root/.cache/torch/hub/checkpoints/resnet152-f82ba261.pth
100.0%
Task exception was never retrieved
future: <Task finished name='Task-950' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/lib/python3.12/site-packages/tornado/websocket.py:1086> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/tornado/websocket.py", line 1088, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/tornado/websocket.py", line 1090, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.


  You can now view your Streamlit app in your browser.

  Network URL: http://172.19.0.27:8501
  External URL: http://213.10.112.40:8501

```

**Comment by mmomjian** [comment]
I’m not sure what is going on but it doesn’t seem like a docker related issue to me. Can you try running it outside Docker to confirm?

**Comment by xinput** [comment]
Hi, 

I'm not using any kind of proxy.
As suggested I tried to run it outside of docker directly on my host. Stuck at the exact same point. 
I additionally just downloaded pytorch and manually place it at /home/user/.cache/torch/hub/checkpoints/ 

restartet the app via streamlit. Same behaviour. Blank window just the sidebar is there where I can enter my immich login settigs.
no additional log files can be found that indicate anything.

**Comment by xinput** [comment]
no idea what could be the issue? :(

**Comment by vale46n1** [comment]
I'll have a look
