### ISSUE TITLE
pip install requirements issue

### ISSUE THREAD

**Issue by dariuszszyc** [vale46n1/immich_duplicate_finder#35]
Hello,

I wanted to give your software a try, but when I executed 
pip install -r requirements.txt

I got this response.
I'm not very advanced and I'm hesitating if I should continue.
I imagine this message could scare away others as well.

What should I do to proceed ?

```
root@omv:/DATA/git/immich_duplicate_finder# pip install -r requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by MrColumbo** [comment]
i am just trying it ilke this

python -m venv venv
source venv/bin/activate
pip install -r requirements.txt


I followed the guide here

https://python.land/virtual-environments/virtualenv#How_to_create_a_Python_venv

**Comment by dariuszszyc** [comment]
Indeed it worked, but with this -pip install downloaded additional 5GB of data. A lot I must say...

**Comment by Fclem** [comment]
This is to be expcted, dependencies on this project are huge. The generated docker image for this is above 6GB 🙄
Since you found a solution, please close this issue.
