### ISSUE TITLE
Trashed assets should be ignored

### ISSUE THREAD

**Issue by agross** [vale46n1/immich_duplicate_finder#7]
I see duplicates being reported for files that are in the Immich trash. I think it makes sense to exclude those when running comparisons.

**Comment by vale46n1** [comment]
Sure. I'll do. In the meantime I would inform that I've decided to proceed with implementing the FAISS way for analyzing assets via the DB API in Immich. The plan is to interfaces directly with Immich's asset database to retrieve images for processing.
https://github.com/immich-app/immich/discussions/1968#discussioncomment-8914723

**Comment by vale46n1** [comment]
I've updated the functionality to include visibility of whether images are marked as favorites or identified as trashed. I'll add a flag to exclude its from the comparison
